### ISSUE TITLE
'Books could not be synced because of errors'

### ISSUE THREAD

**Issue by vivekjones** [hadynz/obsidian-kindle-plugin#133]
I recently integrated this plugin so that I need not subscribe to Readwise. I have never used Readwise and was looking for an alternative to integrate my kindle notes on my Obsidian.

After I downloaded the plugin, I experienced errors as I synced. Here are some observations:

- Some books synced and some books did not
- I signed into my Amazon India account
- I purchased two books on Kindle recently (from amazon.in). One book's highlights are getting synced while the other is not showing up at all.
- The books are not being placed into the folder location (existing folders in vault) that I have designated.

Some reasons for twenty odd books not syncing is perhaps because I have accounts with Amazon.com from my time in the US as well as Amazon.in (current). But the most recent books are both purchased in India Amazon and I am signed into Amazon.in to sync. Any recommendation on books not going to their designated location would also help.

Please help resolve the matter.

Attached is an image of the error.
![Kindlehighlights error](https://user-images.githubusercontent.com/97136782/148144285-bc271ec2-15bc-4621-87e0-80528b6ad8e0.png)

**Comment by Akiyam-hub** [comment]
I  get the same error message.

`4 books(s) could not be synced because of errors`
- Obsidian version 0.13.23
- plugin version: 1.5.2
- region: amazon.jp


### Console message
```console
VM1931:16 Error syncing book {id: "{id}", asin: "{asin}", title: "{author}", url: "https://www.amazon.com/dp/{code}", …} Error: (unknown path)
  TypeError: Cannot read property '0' of undefined
    at Object.r._prettifyError (eval at <anonymous> (app.js:1), <anonymous>:319:1942)
    at t.n.render (eval at <anonymous> (app.js:1), <anonymous>:319:39943)
    at t.n.renderString (eval at <anonymous> (app.js:1), <anonymous>:319:38169)
    at Kt.renderHighlight (eval at <anonymous> (app.js:1), <anonymous>:328:6168)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:328:6263)
    at Array.map (<anonymous>)
    at Kt.renderHighlights (eval at <anonymous> (app.js:1), <anonymous>:328:6251)
    at Kt.render (eval at <anonymous> (app.js:1), <anonymous>:328:5916)
```

I turned off the live preview and tried again, but it didn't help.

**Comment by sljacobson10** [comment]
I am getting the same error with the latest book I purchased for the Kindle (Building a Second Brain).

Obsidian version = 0.15.6
Plugin version = 1.6.3
Region = Amazon Global

Any suggestions on how to get this book to sync?

**Comment by hadynz** [comment]
@vivekjones I know this issue has been open for a while.

Are you able to update to the latest version and let me know if you are still running into the same issue?

**Comment by daoustmark** [comment]
I'm having the same issue. My Amazon library is shared with my kids, which means I sync a lot of Minecraft books...but I'm consistently having one get tripped up on syncing and getting the exact error as listed above. 

Here's the output on console:

`VM152 plugin:obsidian-kindle-plugin:16 Error syncing book {id: '20290', asin: 'B01ERY5QGC', title: 'Minecraft: Diary of a Minecraft Bounty Hunter 6 [U… Minecraft Book] (Mission 2 Team Grieferz Part 6)', author: 'Minecrafters and Wimpy Boy', url: 'https://www.amazon.com/dp/B01ERY5QGC', …} Error: File already exists.
    at t.<anonymous> (app.js:1:1082318)
    at app.js:1:235237
    at Object.next (app.js:1:235342)
    at a (app.js:1:234081)
eval @ VM152 plugin:obsidian-kindle-plugin:16
eval @ plugin:obsidian-kindle-plugin:16
syncBooks @ plugin:obsidian-kindle-plugin:331
await in syncBooks (async)
startSync @ plugin:obsidian-kindle-plugin:331
await in startSync (async)
startAmazonSync @ plugin:obsidian-kindle-plugin:333
onOnlineSync @ plugin:obsidian-kindle-plugin:333
onClick @ plugin:obsidian-kindle-plugin:328
eval @ plugin:obsidian-kindle-plugin:325
r @ plugin:obsidian-kindle-plugin:333`

I'm on the latest plugin version.

**Comment by jrlacalle** [comment]
Hi,
I am getting the same error as it is mentioned in those comments. I get connected to my Amazon account; after a few seconds, the following message appears:
![image](https://user-images.githubusercontent.com/3519975/189544606-4c49b99b-c18d-4bfc-8b42-87cb656c0398.png)

I've tried both in Windows and Mac computer.

Obsidian (Window 0.15.9 & Mac 1.3.1)
Kindle highlight v. 1.6.5
Region: Amazon Spain

**Comment by marianaantunes** [comment]
I was getting the same error, but I was able to solve it by going to the settings and selecting a folder location, that was blank for some reason (maybe I changed the name of the folder and it deselected it). Hope it helps somebody.

![Screenshot 2023-01-18 at 12 45 53](https://user-images.githubusercontent.com/46333060/213218645-a7f6d2de-0f9d-4d88-b25d-9968b9443d11.png)

**Comment by timt1961** [comment]
I had the same issue, with books not syncing. Turned out my Highlights folder location was the problem. This was probably reset after I started moving stuff around.

**Comment by gabrielcassimiro17** [comment]
> I had the same issue, with books not syncing. Turned out my Highlights folder location was the problem. This was probably reset after I started moving stuff around.

This was my problem as well. Changing the sync folder destination worked
